### ISSUE TITLE
Project load error

### ISSUE THREAD

**Issue by seyrinn** [AranoYuki1/VCC-for-mac#1]
Error Domain=NSCocoaErrorDomain Code=260 "The file "vrc-official.json" couldn't be opened because there is no such file."
UserInfo={NSFilePath=/Users/yuki/.local/share/ VRChatCreatorCompanion/Repos/vrc-official.json, NSUnderlyingError=0x600001c621f0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

https://github.com/AranoYuki1/VCC-for-mac/blob/9e894be6f293e6b9dac0798a801d9207d116e714/VCCMac/System/Package/PackageManager.swift#L28
https://github.com/AranoYuki1/VCC-for-mac/blob/9e894be6f293e6b9dac0798a801d9207d116e714/VCCMac/System/Package/PackageManager.swift#L30

These are loading local path.

**Comment by AranoYuki1** [comment]
Thank you!!! And Fixed!!!

**Comment by CuteWaterBeary** [comment]
How was this fixed? I am getting the same error.

2023/06/15 12:44 [error] VCCMac/RepoListView+.swift:56 Error Domain=NSCocoaErrorDomain Code=260 "The file “vrc-official.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/CuteWaterBeary//.local/share/VRChatCreatorCompanion/Repos/vrc-official.json, NSUnderlyingError=0x600001aa9350 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
